version: '3.4'

services:

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=terraform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  terraform-learning:
    container_name: terraform-learning
    image: terraform-learning:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8080
    depends_on:
      - db